### ISSUE TITLE
Generated URL in the views

### ISSUE THREAD

**Issue by tiendunghaui** [ptcong/express-router-wrapper#1]
I have two routers below: 
<code>router.get('/hello/:name', function (req, res, next) {</code>
<code>      res.end('hello ' + req.params.name);</code>
<code>}, {name: 'welcome'});</code>

<code>router.get('/', function (req, res, next) {</code>
   <code> res.render('index', {title: 'Express'});</code>
<code>}); </code>

index.ejs file:
<code>  url('welcome', {name: 'linda'}) </code>
<code>// will generate: '/welcome/linda'</code>

**Comment by ptcong** [comment]
Could you provide your `url()` method ?

**Comment by tiendunghaui** [comment]
I mean I want to make a ‘url()’ function with expected results:

**Comment by tiendunghaui** [comment]
I'm thinking about writing 1 helper but I find writing helper again related to app.locals that module again declared in the router

**Comment by ptcong** [comment]
Yes, you could write a new helper for your template engine or generate URL before assign variables to views

**Comment by kokujin** [comment]
it wold be great to have a helper
